on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Drelease-safe=true
      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir artifact
          if [ "$RUNNER_OS" == "Linux" ]; then
            mv zig-out/bin/Conduit artifact/Conduit
          else
            mv zig-out/bin/Conduit.exe artifact/Conduit.exe
            mv zig-out/bin/Conduit.pdb artifact/Conduit.pdb
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: artifact/

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get build date
        id: date
        shell: bash
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Get short commit hash
        id: vars
        shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
          body: |
            **Build Date:** ${{ steps.date.outputs.date }}
            **Commit:** `${{ steps.vars.outputs.sha_short }}`
          tag_name: latest
          prerelease: true
          make_latest: true
